Visible followers
ITU-BDSA23-GROUP5/Chirp pull request #183
Opened 2023-12-07 18:42 UTC by JakobArnfred

A users number of followers is now shown on the usertimeline. New separate issue is created for creating of tests for this feature

2023-12-07 18:54 UTC, LavenderPlush requested changes
This looks great!
If I understand correctly, this shows only the users own following?

A different solution could be changing the authorDTO to include follower count, so that an additional call the the database wasn't necessary

**Changes**:
It would be nice if the commented code in UserTimeline.cshtml.cs was removed if not used.

2023-12-07 19:20 UTC, Philipnah requested changes
I agree that code that is commented out should be removed. Maybe a check for "if follower count = 1" then show "1 follower" instead of "1 followers"?

2023-12-07 19:20 UTC, Philipnah commented on src/Chirp.Web/Pages/Public/UserTimeline.cshtml.cs
> +	public int followerCount { get; set; }
This should follow the Pascal case naming convention.

2023-12-09 01:41 UTC, Flakiator commented
> This looks great! If I understand correctly, this shows only the users own following?

It also shows other users followers when you visit their profiles! 😎

2023-12-11 14:35 UTC, LavenderPlush approved these changes
These changes look great!

2023-12-11 14:36 UTC, Philipnah approved these changes

2023-12-11 14:37 UTC, merged